// Generated by CoffeeScript 1.6.1
(function() {

  (function($) {
    'use strict';    $.plugin = function(options) {};
    $.plugin["default"] = $.plugin.prototype = {
      _init: function(options) {}
    };
    return $.fn.plugin = function(options) {
      return this.each(function() {});
    };
  })(jQuery);

}).call(this);
