// Generated by CoffeeScript 1.6.1
(function() {

  if (typeof Object.create !== 'function') {
    Object.create = function(obj) {
      var F;
      F = function() {};
      F.prototype = obj;
      return new F();
    };
  }

  (function($, window, document) {
    'use strict';
    var Twitter;
    Twitter = {
      init: function(options, elem) {
        var self;
        self = this;
        self.elem = elem;
        self.$elem = $(elem);
        self.url = 'http://api.twitter.com/1.1/search/tweets.json';
        if (typeof options === 'string') {
          self.search = options;
        } else {
          self.earch = options.search;
        }
        self.options = $.extend({}, $.fn.queryTwitter.options, options);
        return self.refresh(1);
      },
      refresh: function(length) {
        var self;
        self = this;
        return setTimeout(function() {
          return self.fetch().done(function(results) {
            results = self.limit(results.results, self.options.limit);
            self.buildFrag(results);
            self.display();
            if (typeof self.options.onComplete === 'function') {
              self.options.onComplete.apply(self.elem, arguments);
            }
            if (self.options.refresh()) {
              return self.refresh();
            }
          });
        }, length || self.options.refresh);
      },
      fetch: function() {
        return $.ajax({
          url: this.url,
          data: {
            q: this.search
          },
          dataType: 'jsonp'
        });
      },
      buildFrag: function(results) {
        var self;
        self = this;
        return self.tweets = $.map(results, function(obj, i) {
          return $(self.options.wrapEachWith).append(obj.text)[0];
        });
      },
      display: function() {
        var self;
        self = this;
        if (self.options.transition === 'none' || !self.options.transition) {
          return self.$elem.html(self.tweets);
        } else {
          return self.$elem[self.options.transition](500, function() {
            return $(this).html(self.tweets)[self.options.transition](500);
          });
        }
      },
      limit: function(obj, count) {
        return obj.slice(0, count);
      }
    };
    $.fn.queryTwitter = function(options) {
      return this.each(function() {
        var twitter;
        twitter = Object.create(Twitter);
        twitter.init(options, this);
        return $.data(this, 'queryTwitter', twitter);
      });
    };
    return $.fn.queryTwitter.options = {
      search: '@tuspremium',
      wrapEachWith: '<li></li>',
      limit: 10,
      refresh: null,
      onComplete: null,
      transition: 'fadeToggle'
    };
  })(jQuery, window, document);

}).call(this);
